name: Generate Snake Animation

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: salauddinmajumder
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          snake_color: 5bc0be
          background_color: 0d1117

      - name: Push to output branch
        uses: Platane/snk/actions/publish-ghpages@v3
        with:
          repository: salauddinmajumder/salauddinmajumder
